NH-10152: K8s events collection

diff --git a/.github/workflows/buildAndDeploy.yml b/.github/workflows/buildAndDeploy.yml
--- a/.github/workflows/buildAndDeploy.yml
+++ b/.github/workflows/buildAndDeploy.yml
@@ -42,21 +42,37 @@ jobs:
       - name: Deploy services using Skaffold
         run: skaffold run --skip-tests=true
 
-      - name: Tail Otel mock for 60 seconds
+      - name: Tail Otel mock metrics for 60 seconds
         run: |
           mkdir -p OtelLogs
           kubetail timeseries-mock-service --namespace monitoring > OtelLogs/metrics.log &
           sleep 60
-      
+
+      - name: Tail Otel mock events for 60 seconds
+        run: |
+          kubectl delete pods -l component=node-exporter -n monitoring
+          mkdir -p OtelLogs
+          kubetail timeseries-mock-service --namespace monitoring > OtelLogs/events.log &
+          sleep 60
+
       - name: Destroy environment
         run: skaffold delete
 
-      - name: Evaluate functionality
+      - name: Evaluate metrics collection functionality
         run: |
-          if grep -q "k8s." "OtelLogs/metrics.log"; then
+          if grep -q "k8s.kube_pod_info" "OtelLogs/metrics.log"; then
             echo "Expected metrics found"
           else
             echo "Metrics are missing"
+            exit 1
+          fi
+      
+      - name: Evaluate events collection functionality
+        run: |
+          if grep -q "k8s.event." "OtelLogs/events.log"; then
+            echo "Expected events found"
+          else
+            echo "Events are missing"
             exit 1
           fi
 
